name: Build BPB-Wizard

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Build
        run: make build